name: fermi
channels:
  - defaults
dependencies:
  - matplotlib=3.7.1
  - numba=0.56.4
  - numpy=1.23.5
  - python=3.10.9
  - scipy=1.10.0
  - tk=8.6.12
  - pip:
      - dill==0.3.6
      - multiprocess==0.70.14
      - pathos==0.3.0
      - pox==0.3.2
      - ppft==1.7.6.6
      - pyqt5-sip==12.11.0
