name: fermipy
channels:
  - defaults
dependencies:
  - matplotlib==3.10.0
  - numba=0.61.2
  - numpy=2.2.5
  - python=3.13
  - scipy=1.16.0
  - tk
  - pip
  - pytest
  - ipython
  - pip:
      - dill==0.3.6
      - multiprocess==0.70.14
      - pathos==0.3.0
      - pox==0.3.2
      - ppft==1.7.6.6
      - pyqt5-sip==12.11.0
      - pysnooper
